### ISSUE TITLE
Settlement overview window empty after today's update (on beta)

### ISSUE THREAD

**Issue by pnume** [mainIine/foe-helfer-extension#2328]
Hello,

After today's update, the settlement overview window is empty (and shrinked accordingly - I tried to expand it to see if content was just hidden, but no).

Steps:
go to Settlement (Ancient Egypt in my case)
Click the Settlements Overview button in FoE Helper
The box that opens only contains the title 'Settlements Resources Overview - Ancient Egypt' - slightly misaligned (a bit too low, encroaches on the content part of the window, which is empty).

Refreshed, closed and restarted Chrome, repeats every time.

Windows 11 Home
Chrome Version 97.0.4692.71 (Official Build) (64-bit)
beta (Dunarsund)
version 2.6.0.0 - English

Console errors:
FOE Helper version 2.6.0.0 started. ID: bkagcmloachflbbkfmfiggipaelfamdf
_main.js?v=2.6.0.0:2125 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
index:1 Unchecked runtime.lastError: The message port closed before a response was received.
merged-game-4f86dad2.js:9 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
h @ merged-game-4f86dad2.js:9
merged-3rd-party-818a5bbc.js:16 TypeError: Cannot read properties of undefined (reading 'productionBonusProbability')
    at Object.BuildInfoBoxContent (outposts.js?v=2.6.0.0:519:108)
    at Object.BuildInfoBox (outposts.js?v=2.6.0.0:113:12)
    at HTMLSpanElement.<anonymous> (_menu.js?v=2.6.0.0:362:14)
    at HTMLSpanElement.dispatch (merged-3rd-party-818a5bbc.js:3:43064)
    at HTMLSpanElement.v.handle (merged-3rd-party-818a5bbc.js:3:41048)
(anonymous) @ merged-3rd-party-818a5bbc.js:16
merged-3rd-party-818a5bbc.js:16 Updating state in a binding
(anonymous) @ merged-3rd-party-818a5bbc.js:16
merged-3rd-party-818a5bbc.js:16 TypeError: Cannot read properties of undefined (reading 'productionBonusProbability')
    at Object.BuildInfoBoxContent (outposts.js?v=2.6.0.0:519:108)
    at Object.BuildInfoBox (outposts.js?v=2.6.0.0:113:12)
    at HTMLSpanElement.<anonymous> (_menu.js?v=2.6.0.0:362:14)
    at HTMLSpanElement.dispatch (merged-3rd-party-818a5bbc.js:3:43064)
    at HTMLSpanElement.v.handle (merged-3rd-party-818a5bbc.js:3:41048)

Screen capture (I hope this works...)
![image](https://user-images.githubusercontent.com/12427016/155204557-b56b97d5-00bd-4fc2-b5d1-fc5383975fa4.png)

**Comment by pnume** [comment]
Trying the screenshot again: 

![image](https://user-images.githubusercontent.com/12427016/155204920-4c9e2f24-67ef-4121-8dbb-280ec8e2b105.png)

**Comment by Blackfir5** [comment]
hm..also on live server - german - noarsil

**Comment by Ikke01-FoE** [comment]
Same way on the dutch server, reinstalled the extension and the settlement screen stays blank : 

Screen shot : 

![Screenshot_1](https://user-images.githubusercontent.com/100238739/155217487-f9074c2e-2ad5-4a8e-8f05-c5d692bfe742.png)

**Comment by pnume** [comment]
Fixed with new version 2.6.0.1, thank you for your brilliant work.
