### ISSUE TITLE
GB Investment Overview is blank

### ISSUE THREAD

**Issue by Archelaos855** [mainIine/foe-helfer-extension#3085]
![GB  Investment Overview](https://github.com/user-attachments/assets/93341258-5ecb-4272-b738-988ab7346a9e)

**Comment by ianw1974** [comment]
+1 have the same problem for quite a few weeks now.  Not a browser cache problem either.

**Comment by FGk24** [comment]
I noticed I have the same issue - and after fixing the production overview - maybe a copy of the error here would also assist in finding the issue... 

merged-3rd-party-109b844c.js:16  TypeError: Cannot read properties of undefined (reading 'motivatedproducts')
    at Object.RefreshGalaxyBuildings (greatbuildings.js?v=3.8.0.0:673:31)
    at Object.CalcBody (greatbuildings.js?v=3.8.0.0:381:36)
    at Object.Show (greatbuildings.js?v=3.8.0.0:281:24)
    at HTMLSpanElement.<anonymous> (_menu.js?v=3.8.0.0:717:19)
    at HTMLSpanElement.dispatch (merged-3rd-party-109b844c.js:3:43064)
    at v.handle (merged-3rd-party-109b844c.js:3:41048)

**Comment by outoftheline** [comment]
see #2984
