### ISSUE TITLE
Building Efficiency Rating error in version 3.8.1.0 on google chrome

### ISSUE THREAD

**Issue by Slanata** [mainIine/foe-helfer-extension#3097]
When trying to open the result page on the tool "Building efficiency Rating"  nothing happened. In the console is the following error message:
productions.js?v=3.8.1.0:1222 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at productions.js?v=3.8.1.0:1222:31
    at Array.forEach (<anonymous>)
    at Object.showBuildingItems (productions.js?v=3.8.1.0:1202:25)
    at Object.CalcRatingBody (productions.js?v=3.8.1.0:1583:43)
    at HTMLAnchorElement.<anonymous> (productions.js?v=3.8.1.0:1456:17)
    at HTMLDivElement.dispatch (merged-3rd-party-109b844c.js:3:43064)
    at HTMLDivElement.<anonymous> (merged-3rd-party-109b844c.js:3:41048)

**Comment by outoftheline** [comment]
hmpf, I missed this bug when fixing the production overview. 
the error is happening because Inno changed the Sleigh Builders as they will receive an upgrade next winter event.

**Comment by cleopatra16a** [comment]
Bei mir kommt auch kein Ergebnis in der Gebäudeeffizienz

**Comment by outoftheline** [comment]
ja, wie gesagt, hab ich übersehen, muss repariert werden.
